all:delete_info.c free_link.c fun2.c print_fun.c write_fun.c fun1.c main.c declare.h
	gcc  delete_info.c free_link.c fun2.c print_fun.c write_fun.c fun1.c main.c declare.h 
	./a.out
clean:
	rm -rf *.h.gch a.out
