######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 10 23:46:25 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
SOURCES += \
    list.cpp \
    mywidget.cpp

HEADERS += \
    mywidget.h
