######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 12 10:38:33 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += mywidget.h
SOURCES += mywidget.cpp
